- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - vars/vars.yml
  tasks:
  - name: Download Tower user data file
    get_url:
      url: https://raw.githubusercontent.com/mglantz/bicycle/provisioning/tower-prep.sh
      dest: /tmp/tower-prep.sh
      validate_certs: no
      force: yes
      
  - name: Provision Ansible Tower
    ec2:
      aws_access_key: "{{ec2_access_key}}"
      aws_secret_key: "{{ec2_secret_key}}"
      key_name: "{{ec2_key}}"
      region: "{{ ec2_region }}"
      group: "{{ ec2_security_group_tower }}"
      instance_type: t2.medium
      image: "{{ ami_id }}"
      user_data: "{{ lookup('file', '/tmp/tower-prep.sh') }}"
      wait: true
      exact_count: "{{ number_of_tower_systems }}"
      count_tag:
        identity: tower
      instance_tags:
        identity: tower
    register: ec2large
    
  - name: Add Tower instance public IPs to host group
    add_host: hostname={{ item.public_ip }} groups=ec2large
    with_items: "{{ ec2large.tagged_instances }}"
    
  - name: Print IP address of Ansible Tower server
    debug:
      msg: "{{ groups['ec2large'] }}"
      
      
